services:
  # PHP Service (Laravel App)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: learning
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
    networks:
      - learning
    command: php artisan serve --host=0.0.0.0 --port=8000

  # MySQL Service
  db:
    image: mysql:8.0  # ⬅️ Updated version
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: learning
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    networks:
      - learning
    volumes:
      - dbdata:/var/lib/mysql


  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"  # Changed to map host port 8083 to container port 80
    depends_on:
      - db
    networks:
      - learning

      
  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - learning


networks:
  learning:
    driver: bridge

volumes:
  dbdata:
